on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'v0.0.0'
        type: string

permissions:
  id-token: write
  contents: write
  
jobs:
  deploy_infrastructure:
    name: Build
    runs-on: windows-latest

    steps:
      # Checkout code
    - uses: actions/checkout@main
    
    - name: Build
      shell: pwsh
      run: |
        .\Invoke-Build.ps1
    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "Deploy/Install.zip"
        tag: ${{ inputs.version }}
        name: "ShieldChecker ${{ inputs.version }}"
        bodyFile: "CHANGELOG.MD"
        draft: true
        generateReleaseNotes: true
        skipIfReleaseExists: true

